<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-04T16:32:52+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/London',
];
