<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-04T16:41:21+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.doctrine_dev_mode
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.5.2',
    'version_db_installed' => '20190925072210',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1575477172,
        'latest_version' => '8.5.2',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'doctrine_dev_mode' => true,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
