<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-12-04T16:31:18+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Inheritance demo',
        ],
    ],
];
